#!/bin/busybox sh
export PATH=/bin:/usr/bin

/bin/busybox mkdir -p /dev /proc /sys /usr/bin/ /usr/sbin /sbin/
/bin/busybox --install
/bin/busybox --install -s

mount -t proc none /proc
mount -t sysfs none /sys

/sbin/insmod /yaknote.ko

cat << EOF


                  Welcome to the Kwik-E-Mart!

                __________
               / ,--------'
 (            / /     )
  \~~~~~~~~~~/ /~~~~~/
   \ .   O  / /  °  /         Would you like to try some of our
    \      / /     /          slurpees? If you like them, you
     \ *  / /  o  /           can leave a note in our notebook!
      \  /_/ .   /
       \________/
EOF

mknod -m 666 /dev/ttyS0 c 4 64
mknod -m 666 /dev/notebook c 69 0

cttyhack setuidgid 1000 sh

echo "Thank you come again"
/sbin/poweroff -f
